name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: |
        dotnet restore LogisticsCore.csproj
        dotnet restore tests/LogisticsCore.Tests/LogisticsCore.Tests.csproj

    - name: Build
      run: |
        dotnet build LogisticsCore.sln --configuration Release --no-restore
        dotnet build tests/LogisticsCore.Tests/LogisticsCore.Tests.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet run --project tests/LogisticsCore.Tests/LogisticsCore.Tests.csproj --configuration Release --no-build

    - name: Build container image
      run: docker build -t logisticscore:${{ github.sha }} .
